default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ritika
  password: 1234
  host: localhost
  port: 5432
  
development:
  <<: *default
  database: Booking-app-BackEND_development


test:
  <<: *default
  database: Booking-app-BackEND_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>